export enum StatutPaiement {
  EN_ATTENTE_DE_PAIEMENT = 'EN_ATTENTE_DE_PAIEMENT',

  PARTIELLEMENT_PAYEE = 'PARTIELLEMENT_PAYEE',

  EN_RETARD_DE_PAIEMENT = 'EN_RETARD_DE_PAIEMENT',

  PAYEE = 'PAYEE',
}
