export enum TypeMvt {
  ENTREE_DE_STOCK = 'ENTREE_DE_STOCK',

  SORTIE_DE_STOCK = 'SORTIE_DE_STOCK',

  TRANSFERT_DE_STOCK = 'TRANSFERT_DE_STOCK',

  AJUSTEMENT_D_INVENTAIRE = 'AJUSTEMENT_D_INVENTAIRE',
}
